apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: online-boutique

build:
  local:
    push: true
    concurrency: 0
  artifacts:
    - image: ghcr.io/micheal-91/adservice
      context: src/adservice
      docker:
        dockerfile: Dockerfile
    # ... rest of services

# Tell Skaffold to use Kustomize for manifests
manifests:
  kustomize:
    paths:
      - kubernetes-manifests       # folder with kustomization.yaml
