# ~/git_local/kubernetes-manifests/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes-manifests.yaml    # original file with bare names

# Kustomize replaces these — Skaffold updates the tags
images:
  - name: adservice
    newName: ghcr.io/micheal-91/adservice
    newTag: latest                # Skaffold will replace this

  - name: cartservice
    newName: ghcr.io/micheal-91/cartservice
    newTag: latest

  - name: checkoutservice
    newName: ghcr.io/micheal-91/checkoutservice
    newTag: latest

  - name: currencyservice
    newName: ghcr.io/micheal-91/currencyservice
    newTag: latest

  - name: emailservice
    newName: ghcr.io/micheal-91/emailservice
    newTag: latest

  - name: frontend
    newName: ghcr.io/micheal-91/frontend
    newTag: latest

  - name: paymentservice
    newName: ghcr.io/micheal-91/paymentservice
    newTag: latest

  - name: productcatalogservice
    newName: ghcr.io/micheal-91/productcatalogservice
    newTag: latest

  - name: recommendationservice
    newName: ghcr.io/micheal-91/recommendationservice
    newTag: latest

  - name: shippingservice
    newName: ghcr.io/micheal-91/shippingservice
    newTag: latest

  - name: loadgenerator
    newName: ghcr.io/micheal-91/loadgenerator
    newTag: latest
