apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique2
  namespace: argocd
spec:
  project: default2
  source:
    repoURL: "https://github.com/micheal-91/demo_test.git"
    targetRevision: HEAD
    path: .
    directory:
      include: '{test-hydrated-new.yaml}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
